### ISSUE TITLE
GdkPixbufLoader?

### ISSUE THREAD

**Issue by jashephe** [rust-gnome/gdk#11]
Hi, I've been looking around, and I've been having trouble figuring out if [GdkPixbufLoader](https://developer.gnome.org/gdk-pixbuf/2.30/GdkPixbufLoader.html) has been implemented.  Is there any chance that it might be implemented in the future, or has it already been done and am I just looking in the wrong place?  Thanks a lot!

**Comment by GuillaumeGomez** [comment]
No, it hasn't been implemented yet. I'll add it as soon as I can.

**Comment by GuillaumeGomez** [comment]
It'll be good when #12 will be merged.

**Comment by GuillaumeGomez** [comment]
And it's good. Feel free to add any missing you would need !

**Comment by jashephe** [comment]
Awesome — thanks so much!
