### ISSUE TITLE
GErrors as supplementary returns (+ GQuarks and Error domains)

### ISSUE THREAD

**Issue by jashephe** [rust-gnome/gdk#13]
I recently encountered this thanks to the addition of `gdk::PixbufLoader` in #11.  `PixbufLoader`'s function `loader_write(&self, buf: &[u8], error: &mut Error)` requires passing a `GError` (in the form of `gdk::glib::Error`).  [In the GDK documentation](https://developer.gnome.org/gdk-pixbuf/unstable/GdkPixbufLoader.html#gdk-pixbuf-loader-write), the function is looking for a double pointer to memory for an error object, which presumably is only populated when `false` is returned.  In the Rust version, however, we have to pass a fully-instantiated `Error` struct, which can currently only be created with `new_literal(domain: u32, code: i32, message: &str)`.  However, because [`GQuark`](https://developer.gnome.org/glib/stable/glib-Quarks.html)s don't appear to be bridged yet, I cannot successfully create `Error`s because I have no way of determining the domain, and thus cannot write data to `PixbufLoader`s.

It seems to me that the real problem is that the original double-pointer function signature is not reproduced in a Rustic way.  Does anyone have any suggestions?  Thanks!

In the interest of full disclosure, I'm a beginner at all of this, so I might just be missing something obvious.

**Comment by GuillaumeGomez** [comment]
It is reproduced but you just don't see it. Inside the function, we unwrap the pointer and its address to the function. However, it seems I should add a `Error::new()` without params. What do you think of that ?

**Comment by gkoz** [comment]
@jashephe is right, that way doesn't work, we need to accept a new pointer to the error and take ownership of it.

**Comment by GuillaumeGomez** [comment]
Hum... I'll look to do that later in the afternoon then.

**Comment by jashephe** [comment]
Thanks a lot!  I'd love to try to get more involved and help out with this sort of thing, but I'm not really sure how this one should be implemented.

As @gkoz suggests, I think the ideal function signature would look something like 
```rust
fn loader_write(&self, buf: &[u8]) -> Result<(), Error>
```

**Comment by GuillaumeGomez** [comment]
@jashephe: If you want you can try to do this one. You don't have anything to lose and we can help. :-)

**Comment by jashephe** [comment]
Alright, I'll take a look.

**Comment by jashephe** [comment]
Resolved by #15 and #16.
