### ISSUE TITLE
GDK Cairo Interaction

### ISSUE THREAD

**Issue by jashephe** [rust-gnome/gdk#20]
GDK offers a number of [methods for interfacing with Cairo surfaces](https://developer.gnome.org/gdk3/stable/gdk3-Cairo-Interaction.html).  I'd like to see these added, because they can be useful for loading images to render to Cairo surfaces (i.e. `gdk_cairo_set_source_pixbuf()`).  Where would be the best place to add these?  Should they be a part of **rust-gnome/gdk** or would they be better in **rust-gnome/cairo**?

**Comment by GuillaumeGomez** [comment]
The library where to push is the one which start the function's name. In this case, it is `gdk`. Unless there is a strong nonsense to do so, I'd add it to `gdk`.

**Comment by gkoz** [comment]
I don't think they could be put into the cairo crate but traits in Rust allow us to add more methods to `Context` in this crate.
BTW please hold off making any changes to gdk for a day while I'm preparing a GObject refactoring patch.

**Comment by GuillaumeGomez** [comment]
@jashephe: Or you can but you'll certainly need to update your code and I won't merge it until @gkoz is done.

**Comment by jashephe** [comment]
Okay, I can look into adding them as a trait for `Context` (at least, the ones that are appropriate), but I'll wait until @gkoz's changes have landed before I start.

**Comment by GuillaumeGomez** [comment]
Thanks in advance then. :-)
